import React from 'react'
import { Pro } from '@/components/Features/Features'
import AccordionDemo from '@/components/AudioUpload/Instructions'
import Link from 'next/link'
import CodeExec from '@/components/Visualizations/CodeExec';

function ProHome() {
  const inlineStyles = {
    backgroundSize: 'cover',
    backgroundPosition: 'center',
  };
  const proStyles = {
    ...inlineStyles,
    backgroundImage: "url('/home_pro.png')"
  }
  return (
    <div className="flex flex-col gap-4 sm:px-10 pb-4 sm:pb-10 max-w-[800px] mx-auto sm:mt-4">
      <div style={proStyles} className="col-span-1 md:col-span-2 lg:col-span-6 rounded-lg p-4 w-full h-fill">
        <Pro />
      </div>
      <AccordionDemo />
      <Link href='/pro/chat'>
        <div className='w-full p-4 text-center text-on-surface hover:text-surface rounded-full bg-surface hover:bg-on-surface border-on-surface hover:border-surface border-2 transition cursor-pointer'>
          Let&apos;s go
        </div>
      </Link>
      <CodeExec
        parameters={[
          {
            "pitchMidi": 67,
            "amplitude": 0.47556581028870176,
            "pitchBends": [
              0,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ],
            "startTimeSeconds": 4.936808163265306,
            "durationSeconds": 0.16253968253968232
          },
          {
            "pitchMidi": 70,
            "amplitude": 0.5072196112437681,
            "pitchBends": [
              0,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ],
            "startTimeSeconds": 4.809098412698413,
            "durationSeconds": 0.25541950113378675
          },
          {
            "pitchMidi": 84,
            "amplitude": 0.4533706232905388,
            "pitchBends": [
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ],
            "startTimeSeconds": 4.449189115646258,
            "durationSeconds": 0.13931972789115665
          },
          {
            "pitchMidi": 72,
            "amplitude": 0.552259531514398,
            "pitchBends": [
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ],
            "startTimeSeconds": 4.449189115646258,
            "durationSeconds": 0.3366893424036279
          },
          {
            "pitchMidi": 67,
            "amplitude": 0.4726396841662271,
            "pitchBends": [
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ],
            "startTimeSeconds": 3.4378371882086167,
            "durationSeconds": 0.4876190476190474
          },
          {
            "pitchMidi": 40,
            "amplitude": 0.39691309779882433,
            "pitchBends": [
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ],
            "startTimeSeconds": 3.0430979591836733,
            "durationSeconds": 0.23219954648526064
          },
          {
            "pitchMidi": 45,
            "amplitude": 0.4918208258193836,
            "pitchBends": [
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              0,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ],
            "startTimeSeconds": 3.0314879818594105,
            "durationSeconds": 1.3132113378684802
          },
          {
            "pitchMidi": 33,
            "amplitude": 0.7522598860785366,
            "pitchBends": [
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ],
            "startTimeSeconds": 3.019878004535147,
            "durationSeconds": 1.8472702947845803
          },
          {
            "pitchMidi": 69,
            "amplitude": 0.5252644832317646,
            "pitchBends": [
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              0,
              0,
              0,
              0,
              0,
              0,
              1,
              1
            ],
            "startTimeSeconds": 2.694798639455782,
            "durationSeconds": 0.30185941043083897
          },
          {
            "pitchMidi": 72,
            "amplitude": 0.5049967063324792,
            "pitchBends": [
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ],
            "startTimeSeconds": 2.5206489795918365,
            "durationSeconds": 0.16253968253968276
          },
          {
            "pitchMidi": 65,
            "amplitude": 0.5008764327676208,
            "pitchBends": [
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ],
            "startTimeSeconds": 2.369719274376417,
            "durationSeconds": 0.626938775510204
          },
          {
            "pitchMidi": 74,
            "amplitude": 0.5048426596017984,
            "pitchBends": [
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ],
            "startTimeSeconds": 2.1955696145124715,
            "durationSeconds": 0.15092970521541949
          },
          {
            "pitchMidi": 76,
            "amplitude": 0.4081876203417778,
            "pitchBends": [
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ],
            "startTimeSeconds": 2.009809977324263,
            "durationSeconds": 0.1393197278911562
          },
          {
            "pitchMidi": 64,
            "amplitude": 0.48217989848210263,
            "pitchBends": [
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ],
            "startTimeSeconds": 2.009809977324263,
            "durationSeconds": 0.30185941043083897
          },
          {
            "pitchMidi": 62,
            "amplitude": 0.49685377143976983,
            "pitchBends": [
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ],
            "startTimeSeconds": 1.6718367346938776,
            "durationSeconds": 0.6514426303854872
          },
          {
            "pitchMidi": 43,
            "amplitude": 0.43498966785577625,
            "pitchBends": [
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ],
            "startTimeSeconds": 1.6486167800453515,
            "durationSeconds": 0.30185941043083897
          },
          {
            "pitchMidi": 31,
            "amplitude": 0.6906955064489291,
            "pitchBends": [
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ],
            "startTimeSeconds": 1.6486167800453515,
            "durationSeconds": 1.19711156462585
          },
          {
            "pitchMidi": 50,
            "amplitude": 0.39876407012343407,
            "pitchBends": [
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              0,
              0,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ],
            "startTimeSeconds": 0.313469387755102,
            "durationSeconds": 0.6501587301587302
          },
          {
            "pitchMidi": 62,
            "amplitude": 0.3598652978738149,
            "pitchBends": [
              1,
              0,
              0,
              0,
              1,
              1,
              1,
              1,
              1,
              1,
              0,
              0,
              0,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ],
            "startTimeSeconds": 0.2786394557823129,
            "durationSeconds": 0.24380952380952386
          },
          {
            "pitchMidi": 43,
            "amplitude": 0.4917402739747096,
            "pitchBends": [
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ],
            "startTimeSeconds": 0.2786394557823129,
            "durationSeconds": 1.3699773242630386
          },
          {
            "pitchMidi": 53,
            "amplitude": 0.3838653199708284,
            "pitchBends": [
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ],
            "startTimeSeconds": 0.2438095238095238,
            "durationSeconds": 0.7778684807256236
          },
          {
            "pitchMidi": 31,
            "amplitude": 0.7464660585954271,
            "pitchBends": [
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ],
            "startTimeSeconds": 0.29024943310657597,
            "durationSeconds": 1.3467573696145125
          },
          {
            "pitchMidi": 55,
            "amplitude": 0.5309109853686027,
            "pitchBends": [
              0,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              0,
              0,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ],
            "startTimeSeconds": 3.159197732426304,
            "durationSeconds": 1.2203315192743758
          },
          {
            "pitchMidi": 60,
            "amplitude": 0.4111981079691932,
            "pitchBends": [
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ],
            "startTimeSeconds": 3.29851746031746,
            "durationSeconds": 0.24380952380952392
          },
          {
            "pitchMidi": 60,
            "amplitude": 0.40682338636655074,
            "pitchBends": [
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ],
            "startTimeSeconds": 3.6816467120181406,
            "durationSeconds": 0.5933927437641722
          },
          {
            "pitchMidi": 62,
            "amplitude": 0.37130630257967356,
            "pitchBends": [
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ],
            "startTimeSeconds": 0.6733786848072563,
            "durationSeconds": 0.42956916099773235
          },
          {
            "pitchMidi": 53,
            "amplitude": 0.3633650589373804,
            "pitchBends": [
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ],
            "startTimeSeconds": 2.4045492063492064,
            "durationSeconds": 0.359909297052154
          },
          {
            "pitchMidi": 67,
            "amplitude": 0.31467986754749133,
            "pitchBends": [
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ],
            "startTimeSeconds": 4.054449886621315,
            "durationSeconds": 0.26702947845805003
          },
          {
            "pitchMidi": 69,
            "amplitude": 0.3076150448698747,
            "pitchBends": [
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ],
            "startTimeSeconds": 0.6965986394557823,
            "durationSeconds": 0.2205895691609978
          },
          {
            "pitchMidi": 72,
            "amplitude": 0.34444019032849205,
            "pitchBends": [
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1,
              1
            ],
            "startTimeSeconds": 3.1708077097505667,
            "durationSeconds": 0.20897959183673498
          }
        ]}
        code={"function visualizeMidiNotes(midN, container) { const canvas= document.createElement('canvas'); canvas.width = container.clientWidth; canvas.height = container.clientHeight; container.appendChild(canvas); const ctx = canvas.getContext('2d'); ctx.fillStyle = 'white'; ctx.fillRect(0, 0, canvas.width, canvas.height); midN.forEach(note => { const x = (note.startTimeSeconds / 5) * canvas.width; const y = canvas.height - ((note.pitchMidi - 24) / 72) * canvas.height; const width = note.durationSeconds * canvas.width / 5; const height = 2; ctx.fillStyle = 'black'; ctx.fillRect(x, y, width, height);});}"}
        // code={"function visualize(midN, container) {const canvas = document.createElement('canvas');canvas.width = container.clientWidth;canvas.height = container.clientHeight;container.appendChild(canvas);const ctx = canvas.getContext('2d');ctx.fillStyle = 'white';ctx.fillRect(0, 0, canvas.width, canvas.height);const startTime = 0;const endTime = 5;const scaleX = canvas.width / (endTime - startTime);const scaleY = canvas.height / 127;midN.forEach(note => {const x = (note.s - startTime) * scaleX;const y = canvas.height - note.p * scaleY;const width = note.d * scaleX;const height = scaleY;ctx.fillStyle = 'rgba(75, 0, 130, 0.8)';ctx.fillRect(x, y, width, height);});}"}
        // code={"function visualizeMidiNotes(midN, container) { let newDiv = document.createElement('div'); let newText = document.createTextNode('This is some new text.'); newDiv.appendChild(newText); container.appendChild(newDiv);}"}
        // code={"function visualizeNotes(midN, container) {  const canvas = document.createElement('canvas');  canvas.width = container.clientWidth;  canvas.height = container.clientHeight;  container.appendChild(canvas);  const ctx = canvas.getContext('2d');  ctx.fillStyle = 'white';  ctx.fillRect(0, 0, canvas.width, canvas.height);  const noteHeight = 20;  const noteSpacing = 5;  const timeScale = 100;  midN.forEach(note => {    const x = note.s * timeScale;    const y = canvas.height - (note.p - 20) * noteHeight - noteSpacing;    const width = note.d * timeScale;    const height = noteHeight - noteSpacing;    ctx.fillStyle = 'rgba(100, 149, 237, 0.8)';    ctx.fillRect(x, y, width, height);  });}"}
      />
    </div>
  )
}

export default ProHome